version: "2.1"
services:
  jackett:
    image: ghcr.io/linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
      - AUTO_UPDATE=true #optional
      #- RUN_OPTS=<run options here> #optional
    volumes:
      - $HOME/jackett/config:/config
      - $HOME/downloads:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
networks:
  default:
    name: media_net
