version: "2.1"
services:
  lidarr:
    image: ghcr.io/linuxserver/lidarr
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
    volumes:
      - $HOME/lidarr/config:/config
      - $HOME/media/music:/music #permanent folder for media
      - $HOME/downloads:/downloads #general user downloads folder
    ports:
      - 8686:8686
    restart: unless-stopped
networks:
  default:
    name: media_net
