version: "3"
services:
  navidrome:
    image: deluan/navidrome:latest
    ports:
      - "4533:4533"
    environment:
      # Optional: put your config options customization here. Examples:
      ND_SCANINTERVAL: 1m
      ND_LOGLEVEL: info  
      ND_BASEURL: ""
    volumes:
      - "$HOME/navidrome/data:/data"
      - "$HOME/media/music:/music:ro"
networks:
  default:
    name: media_net
