version: "3.7"

services:
  overseerr:
    container_name: overseerr
    image: hotio/overseerr
    restart: unless-stopped
    ports:
      - "5055:5055"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Asia/Kuala_Lumpur
      - ARGS
      - DEBUG=no
    volumes:
      - $HOME/overseerr/config:/config
      # Logo file goes here
      - $HOME/overseerr/logo/logo.png:/app/public.logo.png
