version: "2.1"
services:
  radarr:
    image: ghcr.io/linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
    volumes:
      - data:/config
      - ~/media/Movies:/movies #move from downloads to this permanent folder
      - ~/downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
networks:
  default:
    name: media_net
