version: "2.1"
services:
  rutorrent:
    image: ghcr.io/linuxserver/rutorrent
    container_name: rutorrent
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - $HOME/config:/config
      - $HOME/downloads:/downloads #move from downloads to this permanent folder
    ports:
      - 580:80 #80 port is too generic, might interfere with other services
      - 5000:5000 #scgi port?
      - 56881:51413 #tcp port to download
      - 56881:6881/udp #port forward whatever host port tothe 56881 container port
    restart: unless-stopped
networks:
  default:
    name: media_net
