version: "2.1"
services:
  sonarr:
    image: ghcr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
    volumes:
      - data:/config
      - ~/media/tvshows:/tv #Move from downloads to this permanent folder
      - ~/downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
networks:
  default:
    name: media_net
