version: "3"
services:

  db:
    container_name: wikijs-db
    image: postgres:11-alpine
    environment:
      POSTGRES_DB: wikijs
      POSTGRES_PASSWORD: hahabontot
      POSTGRES_USER: wikijs
    logging:
      driver: "none"
    restart: unless-stopped
    volumes:
      - /volume1/docker/wikijs/db:/var/lib/postgresql/data

  wiki:
    image: requarks/wiki
    container_name: wikijs
    depends_on:
      - db
    environment:
      DB_TYPE: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: wikijs
      DB_PASS: passssss
      DB_NAME: wikijs
    restart: unless-stopped
    ports:
      - "3000:3000"
networks:
  default:
    name: web_net
