version: "2.1"
services:
  wikijs:
    image: ghcr.io/linuxserver/wikijs
    container_name: wikijs
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
    volumes:
      - $HOME/wikijs/config:/config
      - $HOME/wikijs/data:/data
    ports:
      - 3000:3000
    restart: unless-stopped
