version: '3.1'

services:

  wordpress:
    container_name: wordpress
    image: wordpress
    restart: always
    ports:
      - 8484:80 #8080 port is too generic, might interfere with other services
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: wordpressdb
    volumes:
      - $HOME/wordpress/html:/var/www/html

  db:
    container_name: wordpress-db
    image: ghcr.io/linuxserver/mariadb
    restart: always
    environment:
      MYSQL_DATABASE: wordpressdb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_ROOT_PASSWORD: superpass
    volumes:
      - $HOME/wordpress/db:/var/lib/mysql
networks:
  default:
    name: web_net
